export const defaultTheme = {
    colors: {
        border: '#121214',
        white: '#fff',
        background: '#FAFAFA',
        card: '#F3F2F2',
        input: '#EDEDED',
        button: '#E6E5E5',
        hover: '#D7D5D5',
        label: '#8D8686',
        text: '#574F4D',
        subtitle: '#403937',
        title: '#272221',
        purple: '#8047F8',
        'purple-dark': '#4B2995',
        'purple-light': '#EBE5F9',
        yellow: '#C47F17',
        'yellow-dark': '#A47C1B',
        'yellow-light': '#F1E9C9',

    },
    fonts: {
        body: 'Roboto, sans-serif',
        heading: 'Roboto, sans-serif',
        monospace: 'Roboto, sans-serif',
    },
    fontSizes: {
        body: '1rem',
        heading: '1.5rem',
    },
    fontWeights: {
        body: 400,
        heading: 700,
    },
    lineHeights: {
        body: 1.5,
        heading: 1.125,
    },
    space: {
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
    },
    sizes: {
        container: '960px',
    },
    breakpoints: {
        sm: '576px',
        md: '768px',
        lg: '992px',
        xl: '1200px',
    },
}
